repos:
- repo: local
  hooks:
    - id: local-ruff-check
      name: ruff check
      entry: ruff check --force-exclude --fix --exit-non-zero-on-fix
      require_serial: true
      language: unsupported
      types: [python]

    - id: local-ruff-format
      name: ruff format
      entry: ruff format --force-exclude --exit-non-zero-on-format
      require_serial: true
      language: unsupported
      types: [python]






