"""Enrichment functions for the Podcast Analysis Pipeline.

This module creates all the enrichment functions for the Podcast Analysis Pipeline
for reference in the completed script. Enrichments are generated by requesting the
OpenAI API to generate the desired enrichment of podcast transcripts.

Example:
    Typical usage example:

        from enrich_upload.enrichment_functions import some_function
        result = some_function(input_data)

"""

import json
import logging
import os

import boto3
from botocore.client import BaseClient
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()


prompt = """
You are an expert in analyzing podcast transcripts to extract key insights and enrich the data for advertisers.
Your task is to analyze the provided podcast transcript and generate a JSON object containing the following fields:

{
    "sentiment score": float,
    "brand_safety_score": int,
    "summary": "string",
    "hosts": ["string"],
    "guests": ["string"],
    "keywords": [["string", "string"]]
}

Strictly adhere to the following rules for the data fields:

1. **sentiment score**: A float value from -1.00 to 1.00 rounded to 2 decimal places, where -1.00 indicates extremely negative sentiment and 1.00 indicates extremely positive sentiment. 
This score should reflect the overall sentiment of the transcript, taking into account the tone, language, and context of the discussion. 
The sentiment score should be calculated based on the entire transcript, not just individual sentences or sections.


2. **brand_safety_score**: An integer from **0 to 100** representing the suitability of the transcript for brand advertising placement.

**Scoring Philosophy**

The score should follow a **risk-based model**, similar to content rating systems such as PEGI or ESRB, where the presence of certain high-risk content has a disproportionately large impact on the final score. Severe safety concerns should significantly reduce the score even if they occur infrequently.

**Evaluation Criteria**

Analyze the transcript for the presence, severity, prominence, and context of content that may pose a risk to advertisers, including but not limited to:

* Hate speech, discrimination, or extremist content
* Violence, graphic violence, or threats
* Adult, sexual, or explicit content
* Illegal activities, criminal behavior, or dangerous acts
* Self-harm, suicide, or eating disorder content
* Harassment, bullying, or abusive language
* Drug, alcohol, tobacco, or substance abuse content
* Misinformation, conspiracy theories, or harmful medical claims
* Profanity or offensive language
* Politically controversial or highly polarizing topics

**Scoring Methodology**

The score should prioritize the **highest-severity content detected**, not merely the average content quality.

Apply the following principles:

* A single instance of severe unsafe content can substantially lower the score.
* Multiple categories of unsafe content should compound penalties.
* Content that is graphic, celebratory, instructional, promotional, or encouraging of harmful behavior should receive stronger penalties than neutral discussion.
* Repeated exposure to unsafe content should further reduce the score.
* Educational, journalistic, documentary, historical, or critical discussion may mitigate penalties but should not eliminate them entirely.

**Interpretation Guide**

* **90–100:** Very safe for most brands; no meaningful safety concerns.
* **75–89:** Generally safe; contains mild profanity, mature themes, or limited controversial discussion.
* **50–74:** Moderate risk; contains recurring mature, violent, political, or sensitive content.
* **25–49:** High risk; contains explicit discussions of violence, sex, drugs, hate, or other advertiser-sensitive topics.
* **0–24:** Severe risk; contains graphic violence, hate speech, extremism, explicit sexual content, criminal instruction, self-harm promotion, or other content that many advertisers would categorically avoid.

When uncertain between two scores, choose the lower score if advertiser risk is plausible.


3. **summary**: A clear, concise and compelling summary of the podcast episode, limited to 2 sentences. 
The summary should capture the main topics discussed, the overall theme of the episode, and any key insights or takeaways that would be relevant and interesting for advertisers.
 The summary should be written in a way that is engaging and informative, providing a snapshot of what the episode is about without giving away too much detail.

4. **hosts**: Extract the names of the hosts mentioned in the transcript as a list of strings. If no hosts are explicitly mentioned, return an empty list.

5. **guests**: Extract the names of the guests mentioned in the transcript as a list of strings. If no guests are explicitly mentioned, return an empty list.


6. **keywords**: A list of the top 10 most relevant keywords extracted from the transcript, where each keyword is represented as a 2-element array containing the keyword in lowercase and the word "topic" as the second element.
A keyword should capture a general topic, overarching theme, or person discussed in the transcript.
The keywords should be extracted based on their relevance and frequency in the transcript, not just their presence. Preference should be given for keywords which would be the most interesting and relevant for advertisers.


"""


def prompt_llm_for_enrichment(openai_client: OpenAI, transcript: str) -> dict:
    """Generates a summary of the podcast transcript using the OpenAI API.

    Args:
        openai_client (OpenAI): The initialized OpenAI client.
        transcript (str): The podcast transcript to be summarized.

    Returns:
        dict: A dictionary containing the enriched information from the podcast transcript.

    Raises:
        Exception: If there is an error generating the enrichment from the OpenAI API,
        an exception will be raised with the error message.
    """

    try:
        logging.info("Analyzing podcast transcript for enriched data.")
        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": prompt,
                },
                {"role": "user", "content": f"This is your text to analyze: {transcript}"},
            ],
        )
        logging.info("Transcript analysis completed successfully.")

        # Extract content and clean markdown formatting if present
        content = response.choices[0].message.content

        # Ensure content is not None
        if content is None:
            raise ValueError("LLM response returned empty content")

        # Remove markdown code blocks if present
        if content.startswith("```"):
            # Remove ```json or ``` from start and ``` from end
            content = content.lstrip("`")  # Remove leading backticks
            if content.startswith("json"):
                content = content[4:].lstrip()  # Remove "json" prefix
            content = content.rstrip("`").strip()  # Remove trailing backticks

        logging.info(f"Cleaned response content: {content[:100]}...")
        return json.loads(content)

    except json.JSONDecodeError as e:
        logging.error(f"Failed to parse LLM response as JSON: {e}. Response: {content}")
        raise ValueError(f"LLM response is not valid JSON: {e}") from e
    except Exception as e:
        logging.error(f"Failed to analyze transcript: {e}")
        raise


# def prompt_llm_for_moderation(llm_client: oa.OpenAI, transcript: str) -> dict:
#     """Generates a moderation analysis of the podcast transcript using the OpenAI API.

#     Args:
#         llm_client (oa.OpenAI): The initialized OpenAI client.
#         transcript (str): The podcast transcript to be analyzed.

#     Returns:
#         dict: A dictionary containing the moderation analysis from the podcast transcript
#         keys have boolean values.

#     Raises:
#         Exception: If there is an error generating the moderation analysis from the OpenAI API,
#         an exception will be raised with the error message.
#     """

#     try:
#         logging.info("Analyzing podcast transcript for moderation.")
#         response = llm_client.moderations.create(
#             model="omni-moderation-latest",
#             input=transcript,
#         )
#         logging.info("Transcript moderation analysis completed successfully.")
#         return response.results[0].categories.model_dump()

#     except Exception as e:
#         logging.error(f"Failed to analyze transcript for moderation: {e}")
#         raise


def get_episode_metadata_from_s3(s3_client: BaseClient, s3_path: str) -> dict:
    """Retrieves the podcast transcript and additional metadata from S3.

    Args:
        s3_client (BaseClient): The initialized S3 client.
        s3_path (str): The S3 path to the specific episode directory,
        e.g., 's3://bucket_name/object_key'.

    Returns:
        dict: A dictionary containing the podcast transcript and additional metadata.

    Raises:
        TypeError: If the S3 path is not a string.
        ValueError: If the S3 path does not start with 's3://'.
        Exception: If there is an error retrieving the metadata from S3, an
        exception will be raised with the error message.

    """

    if not isinstance(s3_path, str):
        raise TypeError("S3 path must be a string")
    if not s3_path.startswith("s3://"):
        raise ValueError("S3 path invalid: S3 path must start with 's3://'")

    try:
        bucket_name = s3_path.split("/")[2].strip()
        object_key = "/".join(s3_path.split("/")[3:]).strip()
        if object_key and not object_key.endswith("/"):
            object_key += "/"

        metadata = s3_client.get_object(Bucket=bucket_name, Key=f"{object_key}metadata.json")
        logging.info("Metadata retrieved successfully from S3.")

        return json.loads(metadata["Body"].read().decode("utf-8"))
    except Exception as e:
        logging.error(f"Failed to retrieve metadata from S3: {e}")
        raise


def get_episode_transcript_from_s3(s3_client: BaseClient, s3_path: str) -> str:
    """Retrieves the podcast transcript from S3.

    Args:
        s3_client (BaseClient): The initialized S3 client.
        s3_path (str): The S3 path to the specific episode directory, e.g., 's3://bucket_name/object_key'.

    Returns:
        str: The podcast transcript as a string.


    Raises:
        TypeError: If the S3 path is not a string.
        ValueError: If the S3 path does not start with 's3://'.
        Exception: If there is an error retrieving the transcript from S3, an exception will be
        raised with the error message.
    """

    if not isinstance(s3_path, str):
        raise TypeError("S3 path must be a string")
    if not s3_path.startswith("s3://"):
        raise ValueError("S3 path invalid: S3 path must start with 's3://'")

    try:
        bucket_name = s3_path.split("/")[2].strip()
        object_key = "/".join(s3_path.split("/")[3:]).strip()
        if object_key and not object_key.endswith("/"):
            object_key += "/"

        transcript = s3_client.get_object(Bucket=bucket_name, Key=f"{object_key}transcript.txt")
        logging.info("Transcript retrieved successfully from S3.")

        return transcript["Body"].read().decode("utf-8")
    except Exception as e:
        logging.error(f"Failed to retrieve transcript from S3: {e}")
        raise


if __name__ == "__main__":
    s3_client = boto3.client("s3")
    openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    s3_path = "s3://c23-podex-ai-bucket/8/73/"
    transcript = get_episode_transcript_from_s3(s3_client, s3_path)
    enrichment = prompt_llm_for_enrichment(openai_client, transcript)
    print(enrichment)
