"""Enrichment functions for the Podcast Analysis Pipeline.

This module creates all the enrichment functions for the Podcast Analysis Pipeline
for reference in the completed script. Enrichments are generated by requesting the
OpenAI API to generate the desired enrichment of podcast transcripts.

Example:
    Typical usage example:

        from enrich_upload.enrichment_functions import some_function
        result = some_function(input_data)

"""

import json
import logging

import boto3
import openai as oa
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file


prompt = """
You are an expert data analyst specializing in Natural Language Processing (NLP),
sentiment analysis, and data enrichment.

Analyze the text provided at the end of this prompt and return the results strictly as a
valid JSON object. Do not include any of your own conversational intro or
outro text. Use the exact JSON structure defined below:

{

    "sentiment score": float,
    "classification": "string",
    "summary": "string",
    "hosts": ["string"],
    "guests": ["string"],
    "keywords": [["string", "string"]]
}

Strictly adhere to the following rules for the data fields:
1. **sentiment score**: A float value from 0.00 to 5.00 rounded to 2 decimal places.
(0.00 = extremely negative, 5.00 = extremely positive) reflecting the overall
sentiment of the transcript.
2. **classification**: Map the score using these precise boundaries:
   - 0.00 to 0.99: "very negative"
   - 1.00 to 1.99: "negative"
   - 2.00 to 2.99: "neutral"
   - 3.00 to 3.99: "positive"
   - 4.00 to 5.00: "very positive"
3. **summary**: A concise summary of the podcast episode in 3-5 sentences.
4. **hosts**: Extract the names of the hosts mentioned in the transcript as a list of strings.
If no hosts are explicitly mentioned, return an empty list.
5. **guests**: Extract the names of the guests mentioned in the transcript as a list of strings.
If no guests are explicitly mentioned, return an empty list.
6. **keywords**: A JSON array where each element is a 2-element array containing a lowercase keyword
and its category. Each keyword should capture a general topic, location, overarching theme, or
individual discussed. The category should be from the white list below.

Category White List:
- "topic": A general topic or subject matter discussed in the episode
    (e.g., "technology", "health", "sports").
- "location": A specific location mentioned in the episode
    (e.g., "New York", "Paris", "Tokyo").
- "concept": An overarching theme, idea, or concept discussed in the episode
    (e.g., "innovation", "sustainability", "leadership").
- "individual": A specific person mentioned in the episode
    (e.g., "Elon Musk", "Oprah Winfrey", "Barack Obama").
- "product and IP": A specific product, company, or intellectual property mentioned
    in the episode (e.g., "iPhone", "Tesla", "Marvel Cinematic Universe").
- "role and sector": A specific role, industry, or sector mentioned in the episode
    (e.g., "software engineer", "finance", "healthcare").
- "advert": A specific advertisement or brand mentioned in the episode, and explicitly stated
    as a sponsor / partnership (e.g., "Nike", "Coca-Cola", "Amazon").
- "current event": A specific current event mentioned in the episode
    (e.g., "2024 Olympics", "2024 US Presidential Election", "COVID-19 pandemic").
- "other": A keyword that does not fit into any of the above categories,
    but is still a significant and relevant keyword from the episode.

"""


def prompt_llm_for_enrichment(llm_client: oa.OpenAI, transcript: str) -> dict:
    """Generates a summary of the podcast transcript using the OpenAI API.

    Args:
        llm_client (oa.OpenAI): The initialized OpenAI client.
        transcript (str): The podcast transcript to be summarized.

    Returns:
        dict: A dictionary containing the enriched information from the podcast transcript.

    Raises:
        Exception: If there is an error generating the enrichment from the OpenAI API,
        an exception will be raised with the error message.
    """

    try:
        logging.info("Analyzing podcast transcript for enriched data.")
        response = llm_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": prompt,
                },
                {"role": "user", "content": f"This is your text to analyze: {transcript}"},
            ],
        )
        logging.info("Transcript analysis completed successfully.")

        # Extract content and clean markdown formatting if present
        content = response.choices[0].message.content.strip()

        # Remove markdown code blocks if present
        if content.startswith("```"):
            # Remove ```json or ``` from start and ``` from end
            content = content.lstrip("`")  # Remove leading backticks
            if content.startswith("json"):
                content = content[4:].lstrip()  # Remove "json" prefix
            content = content.rstrip("`").strip()  # Remove trailing backticks

        logging.info(f"Cleaned response content: {content[:100]}...")
        return json.loads(content)
    except json.JSONDecodeError as e:
        logging.error(f"Failed to parse LLM response as JSON: {e}. Response: {content}")
        raise ValueError(f"LLM response is not valid JSON: {e}") from e
    except Exception as e:
        logging.error(f"Failed to analyze transcript: {e}")
        raise


def get_episode_metadata_from_s3(s3_client: boto3.client, s3_path: str) -> dict:
    """Retrieves the podcast transcript and additional metadata from S3.

    Args:
        s3_client (boto3.client): The initialized S3 client.
        s3_path (str): The S3 path to the specific episode directory, e.g., 's3://bucket_name/object_key'.

    Returns:
        dict: A dictionary containing the podcast transcript and additional metadata.

    Raises:
        TypeError: If the S3 path is not a string.
        ValueError: If the S3 path does not start with 's3://'.
        Exception: If there is an error retrieving the transcript from S3, an
        exception will be raised with the error message.

    """

    if not isinstance(s3_path, str):
        raise TypeError("S3 path must be a string")
    if not s3_path.startswith("s3://"):
        raise ValueError("S3 path invalid: S3 path must start with 's3://'")

    try:
        bucket_name = s3_path.split("/")[2].strip()
        object_key = "/".join(s3_path.split("/")[3:]).strip()
        if object_key and not object_key.endswith("/"):
            object_key += "/"

        metadata = s3_client.get_object(Bucket=bucket_name, Key=f"{object_key}metadata.json")
        logging.info("Metadata retrieved successfully from S3.")

        return json.loads(metadata["Body"].read().decode("utf-8"))
    except Exception as e:
        logging.error(f"Failed to retrieve metadata from S3: {e}")
        raise


def get_episode_transcript_from_s3(s3_client: boto3.client, s3_path: str) -> str:
    """Retrieves the podcast transcript from S3.

    Args:
        s3_client (boto3.client): The initialized S3 client.
        s3_path (str): The S3 path to the specific episode directory, e.g., 's3://bucket_name/object_key'.

    Returns:
        str: The podcast transcript as a string.


    Raises:
        TypeError: If the S3 path is not a string.
        ValueError: If the S3 path does not start with 's3://'.
        Exception: If there is an error retrieving the transcript from S3, an exception will be
        raised with the error message.
    """

    if not isinstance(s3_path, str):
        raise TypeError("S3 path must be a string")
    if not s3_path.startswith("s3://"):
        raise ValueError("S3 path invalid: S3 path must start with 's3://'")

    try:
        bucket_name = s3_path.split("/")[2].strip()
        object_key = "/".join(s3_path.split("/")[3:]).strip()
        if object_key and not object_key.endswith("/"):
            object_key += "/"

        transcript = s3_client.get_object(Bucket=bucket_name, Key=f"{object_key}transcript.txt")
        logging.info("Transcript retrieved successfully from S3.")

        return transcript["Body"].read().decode("utf-8")
    except Exception as e:
        logging.error(f"Failed to retrieve transcript from S3: {e}")
        raise
